/**
 * Generate package.json for the output project.
 */
export function generatePackageJson(meta) {
  const pkg = {
    name: meta.name || 'my-electron-app',
    version: meta.version || '0.1.0',
    description: `Generated by Muon — ${meta.name}`,
    main: '.webpack/main',
    scripts: {
      start: 'electron-forge start',
      package: 'electron-forge package',
      make: 'electron-forge make',
    },
    dependencies: {
      'electron-squirrel-startup': '^1.0.1',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      zustand: '^4.5.0',
    },
    devDependencies: {
      '@babel/core': '^7.24.0',
      '@babel/preset-env': '^7.24.0',
      '@babel/preset-react': '^7.23.3',
      '@electron-forge/cli': '^7.3.0',
      '@electron-forge/maker-deb': '^7.3.0',
      '@electron-forge/maker-squirrel': '^7.3.0',
      '@electron-forge/maker-zip': '^7.3.0',
      '@electron-forge/plugin-auto-unpack-natives': '^7.3.0',
      '@electron-forge/plugin-webpack': '^7.3.0',
      '@vercel/webpack-asset-relocator-loader': '^1.7.3',
      'babel-loader': '^9.1.3',
      'css-loader': '^6.10.0',
      electron: meta.electron || '^28.2.0',
      'html-webpack-plugin': '^5.6.0',
      'node-loader': '^2.0.0',
      'style-loader': '^3.3.4',
    },
  };

  return JSON.stringify(pkg, null, 2) + '\n';
}
